name: add-to-project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-issue-to-project:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.ADD_TO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  add-pr-to-project:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to GitHub Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ vars.ADD_TO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
